name: 'Submit deployment data to Jira'
description: 'Submit deployment data to Jira Cloud'
author: 'spex'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  clientId:
    description: 'Access token found in OAth credentials of your Jira Cloud website'
    required: true
  clientSecret:
    description: 'Access token found in OAth credentials of your Jira Cloud website'
    required: true
  baseUrl:
    description: 'The base URL of your connected Jira Cloud.'
    required: true
  deploymentSequenceNumber:
    description: 'This is the identifier for the deployment. It must be unique for the specified pipeline and environment. It must be a monotonically increasing number, as this is used to sequence the deployments. `env.GITHUB_RUN_ID` by default'
    required: false
  updateSequenceNumber:
    description: 'A number used to apply an order to the updates to the deployment, as identified by the deploymentSequenceNumber, in the case of out-of-order receipt of update requests. It must be a monotonically increasing number. `env.GITHUB_RUN_NUMBER` by default'
    required: false
  jiraKeys:
    description: 'Jira issue keys to update Deployment Data'
    required: false
  displayName:
    description: 'The human-readable name for the deployment. Will be shown in the UI.'
    required: true
  url:
    description: 'A URL users can use to link to this deployment, in this environment.'
    required: false
  description:
    description: 'A short description of the deployment'
    required: false
  lastUpdated:
    description: 'The last-updated timestamp to present to the user as a summary of the state of the deployment.'
    required: true
  label:
    description: 'An (optional) additional label that may be displayed with deployment information.'
    required: false
  state:
    description: 'The state of the deployment'
    required: true
  pipelineId:
    description: 'The identifier of this pipeline, must be unique for the provider.'
    required: false
  pipelineDisplayName:
    description: 'The name of the pipeline to present to the user.'
    required: false
  pipelineUrl:
    description: 'A URL users can use to link to this deployment pipeline.'
    required: false
  environmentId:
    description: 'The identifier of this environment, must be unique for the provider so that it can be shared across pipelines.'
    required: true
  environmentDisplayName:
    description: 'The name of the environment to present to the user.'
    required: true
  environmentType:
    description: 'The type of the environment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
